Dev
nathandroberts/sparta-tic-tac-toe pull request #1
Opened 2017-11-02 22:57 UTC by nathandroberts

2017-11-03 11:46 UTC, JSChilds commented on script.js
> +    alert('winner x')
Is there a better way you could get this information to the player than an alert?

2017-11-03 11:47 UTC, JSChilds commented on script.js
> +  $(this).addClass('X').html('X')
This should be indented.

2017-11-03 11:48 UTC, JSChilds requested changes
Very close and your code is clear and readable. Consider using what you learned in the homework review to complete this.

2017-11-05 19:46 UTC, nathandroberts commented
Winner now displayed in text rather than as an alert

2017-11-06 09:51 UTC, JSChilds approved these changes

2017-11-06 09:51 UTC, merged